resources:
  - namespace.yml
  - application.yml

# helmCharts:
#   - name: longhorn
#     repo: https://charts.longhorn.io
#     releaseName: longhorn
#     version: 1.7.2
#     namespace: longhorn-system
#     valuesInline:
#       preUpgradeChecker:
#         jobEnabled: false
#       global:
#         tolerations:
#           - key: node-role.kubernetes.io/master
#             operator: Exists
#             effect: NoSchedule
#           - key: node.kubernetes.io/control-plane
#             operator: Exists
#             effect: NoSchedule
