---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
spec:
  destination:
    namespace: gatus-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gatus
    helm:
      values: |
        config:
          ui:
            header: 'mtaha.dev - Health Status'
            title: 'Health Status | mtaha.dev'
          endpoints:
            #- name: 'ArgoCD'
            #  url: 'https://argo.mtaha.dev'
            #  group: 'internal'
            #  interval: 300s
            #  conditions:
            #    - '[STATUS] == any(200, 201, 202)'
            - name: 'Nextcloud'
              url: 'https://cloud.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Grafana'
              url: 'https://dash.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Filestash'
              url: 'https://files.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'CodiMD'
              url: 'https://md.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Memos'
              url: 'https://notes.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Paperless-NGX'
              url: 'https://paperless.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Commafeed'
              url: 'https://rss.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'MinIO'
              url: 'https://s3.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Umami'
              url: 'https://umami.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
            - name: 'Vaultwarden'
              url: 'https://vault.mtaha.dev'
              group: 'internal'
              interval: 300s
              conditions:
                - '[STATUS] == any(200, 201, 202)'
    repoURL: https://twin.github.io/helm-charts
    targetRevision: 1.*
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
