---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argocd
spec:
  destination:
    namespace: umami-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: umami
    helm:
      parameters:
      - name: global.main.appSecret.autoCreate
        value: kustomize
      - name: global.postgresql.secret.autoCreate
        value: kustomize
      - name: global.postgresql.cnpg.enabled
        value: "true"
      - name: global.postgresql.cnpg.replicas
        value: "1"
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true