---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami
  namespace: umami-k8s
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`umami.mtaha.dev`)
      priority: 10
      services:
        - kind: Service
          name: umami-web
          namespace: umami-k8s
          passHostHeader: true
          port: 3000
          scheme: http
  tls:
    domains:
      - main: umami.mtaha.dev
    secretName: wildcard-mtaha.dev-tls
