resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: umami-web
    namespace: umami-k8s
    envs:
      - ./.app-secret.env
  - name: umami-postgres
    namespace: umami-k8s
    envs:
      - ./.db-secret.env
