---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vaultwarden
    helm:
      parameters:
      - name: global.postgres.secret.name
        value: vaultwarden-postgres
      - name: global.postgres.secret.databaseKey
        value: postgres_database
      - name: global.postgres.secret.usernameKey
        value: postgres_username
      - name: global.postgres.secret.passwordKey
        value: postgres_password
      - name: global.postgres.secret.autoCreate
        value: "kustomize"
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true