---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vaultwarden
    helm:
      parameters:
      - name: global.postgresql.secret.name
        value: vaultwarden-postgresql
      - name: global.postgresql.secret.databaseKey
        value: database
      - name: global.postgresql.secret.usernameKey
        value: username
      - name: global.postgresql.secret.passwordKey
        value: password
      - name: global.postgresql.secret.autoCreate
        value: kustomize
      - name: global.postgresql.cnpg.enabled
        value: "true"
      - name: global.postgresql.cnpg.replicas
        value: "1"
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true