resources:
  - namespace.yml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    version: 8.3.7
    namespace: argocd
    valuesInline:
      configs:
        params:
          server.insecure: true
      global:
        domain: argo.mtaha.dev