---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine
  namespace: argocd
spec:
  destination:
    namespace: redmine-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redmine
    helm:
      parameters:
      - name: global.postgres.secret.name
        value: redmine-postgres
      - name: global.postgres.secret.databaseKey
        value: database
      - name: global.postgres.secret.usernameKey
        value: username
      - name: global.postgres.secret.passwordKey
        value: password
      - name: global.postgres.secret.autoCreate
        value: kustomize
      - name: global.postgres.cnpg.enabled
        value: "true"
      - name: global.postgres.cnpg.replicas
        value: "1"
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true