resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: redmine-postgres
    namespace: redmine-k8s
    envs:
      - ./.db-secret.env