resources:
  - namespace.yml
  - subnet-router.yml
  - application.yml

# helmCharts:
#   - name: tailscale-operator
#     repo: https://pkgs.tailscale.com/helmcharts
#     releaseName: tailscale-operator
#     version: 1.78.3
#     namespace: tailscale-k8s
#     valuesInline:
#       operatorConfig:
#         defaulTags:
#           - tag:k8s-operator
#       proxyConfig:
#         defaultTags: tag:k8s-pods

secretGenerator:
  - name: operator-oauth
    namespace: tailscale-k8s
    envs:
      - ./.operator-secret.env
  - name: tailscale-auth
    namespace: tailscale-k8s
    envs:
      - ./.tailscale-secret.env