---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filestash
  namespace: argocd
spec:
  destination:
    namespace: filestash-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: filestash
    helm:
      parameters:
      - name: main.options.application_url
        value: files.mtaha.dev
      values: |-
        nodeSelector:
          kubernetes.io/hostname: w2.srv.mtaha.dev
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true