---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    namespace: nextcloud-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nextcloud
    helm:
      parameters:
      - name: cronjob.enabled
        value: "true"
      - name: image.flavor
        value: fpm
      values: |
        nextcloud:
          host: "cloud.mtaha.dev"
          username: "administrator"
          password: "my_strong_password"

          configs:
            custom.config.php: |
              <?php
              $CONFIG = array (
                'trusted_domains' =>
                array (
                  0 => 'cloud.mtaha.dev',
                ),
                'overwrite.cli.url' => 'https://cloud.mtaha.dev',
                'overwriteprotocol' => 'https',
                'default_phone_region' => 'TR',
                'trusted_proxies' =>
                array (
                  0 => '127.0.0.1',
                ),
                'maintenance_window_start' => 1,
              );
          phpConfigs:
            zz-nc-custom.ini: |-
              memory_limit = 512M
              upload_max_filesize = 2G
              post_max_size = 600M
              max_execution_time = 300
              file_uploads = On
              allow_url_fopen = On

        internalDatabase:
          enabled: false

        nginx:
          enabled: true

        externalDatabase:
          enabled: true
          type: postgresql
          user: nextcloud
          password: my_strong_password
          database: nextcloud
          existingSecret:
            enabled: false

        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: nextcloud
                password: my_strong_password
                database: nextcloud

          primary:
            persistence:
              enabled: true
              accessMode: ReadWriteOnce
              size: 2Gi

        #redis:
          #enabled: true
          #auth:
            #enabled: true
            #existingSecret: "nextcloud-db"
            #existingSecretPasswordKey: "redis-password"

        replicaCount: 1

        persistence:
          enabled: true
          # Use an existing Persistent Volume Claim (must be created ahead of time)
          #existingClaim: nextcloud
          # storageClass: ""
          accessMode: ReadWriteOnce
          size: 32Gi
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.*
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true