---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
  namespace: nextcloud-k8s
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cloud.mtaha.dev`)
      priority: 10
      services:
        - kind: Service
          name: nextcloud
          namespace: nextcloud-k8s
          passHostHeader: true
          port: 8080
          scheme: http
  tls:
    domains:
      - main: cloud.mtaha.dev
    secretName: wildcard-mtaha.dev-tls
