resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: paperless-ngx-secret
    namespace: paperless-ngx-k8s
    envs:
      - ./.app-secret.env
  - name: paperless-ngx-postgresql
    namespace: paperless-ngx-k8s
    envs:
      - ./.db-secret.env