---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-m1
  namespace: default
spec:
  containers:
    - name: dnsutils-m1
      image: registry.k8s.io/e2e-test-images/agnhost:2.39
      command:
        - sleep
        - 'infinity'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: m1.srv.mtaha.dev
  tolerations:
    - key: 'node-role.kubernetes.io/control-plane'
      operator: 'Exists'
      effect: 'NoSchedule'
    - key: 'node-role.kubernetes.io/master'
      operator: 'Exists'
      effect: 'NoSchedule'
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-w1
  namespace: default
spec:
  containers:
    - name: dnsutils-w1
      image: registry.k8s.io/e2e-test-images/agnhost:2.39
      command:
        - sleep
        - 'infinity'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: w1.srv.mtaha.dev
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-w2
  namespace: default
spec:
  containers:
    - name: dnsutils-w2
      image: registry.k8s.io/e2e-test-images/agnhost:2.39
      command:
        - sleep
        - 'infinity'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: w2.srv.mtaha.dev
