---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  destination:
    namespace: vikunja-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vikunja
    helm:
      parameters:
      - name: global.main.options.publicurl
        value: https://plan.mtaha.dev
      - name: global.main.appSecret.autoCreate
        value: kustomize
      - name: global.postgresql.secret.autoCreate
        value: kustomize
      - name: global.postgresql.cnpg.enabled
        value: "true"
      - name: global.postgresql.cnpg.replicas
        value: "1"
      values: |-
        global:
          main:
            environments:
              - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
                value: false
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true