---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  destination:
    namespace: vikunja-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vikunja
    helm:
      parameters:
      - name: main.options.publicurl
        value: https://plan.mtaha.dev
      - name: main.appSecret.autoCreate
        value: kustomize
      - name: postgresql.secret.autoCreate
        value: kustomize
      values: |-
        main:
          environments:
            - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
              value: false
        nodeSelector:
          kubernetes.io/hostname: w1.srv.mtaha.dev
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true