resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: vikunja-secret
    namespace: vikunja-k8s
    envs:
      - ./.app-secret.env
  - name: vikunja-postgresql
    namespace: vikunja-k8s
    envs:
      - ./.db-secret.env