---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codimd
  namespace: argocd
spec:
  destination:
    namespace: codimd-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: codimd
    helm:
      parameters:
      - name: global.web.options.codimd_domain
        value: md.mtaha.dev
      - name: global.postgres.secret.name
        value: codimd-postgres
      - name: global.postgres.secret.databaseKey
        value: database
      - name: global.postgres.secret.usernameKey
        value: username
      - name: global.postgres.secret.passwordKey
        value: password
      - name: global.postgres.secret.autoCreate
        value: kustomize
      - name: global.postgres.external.enabled
        value: "false"
      - name: global.postgres.cnpg.enabled
        value: "true"
      - name: global.postgres.cnpg.replicas
        value: "1"
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true