---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codimd
  namespace: argocd
spec:
  destination:
    namespace: codimd-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: codimd
    helm:
      parameters:
      - name: global.web.options.codimd_domain
        value: md.mtaha.dev
      - name: global.postgres.secret.name
        value: codimd-postgres
      - name: global.postgres.secret.databaseKey
        value: postgres_database
      - name: global.postgres.secret.usernameKey
        value: postgres_username
      - name: global.postgres.secret.passwordKey
        value: postgres_password
      - name: global.postgres.secret.autoCreate
        value: "kustomize"
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true