---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codimd
  namespace: argocd
spec:
  destination:
    namespace: codimd-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: codimd
    helm:
      parameters:
        - name: global.web.options.codimd_domain
          value: md.mtaha.dev
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
