resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: codimd-postgres
    namespace: codimd-k8s
    envs:
      - ./.db-secret.env
  - name: basic-auth-secret
    namespace: codimd-k8s
    type: kubernetes.io/basic-auth
    envs:
      - ./.basic-auth-secret.env
