---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-reflector
  namespace: argocd
spec:
  destination:
    namespace: kubernetes-reflector
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 7.*
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true