---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anki-server
  namespace: argocd
spec:
  destination:
    namespace: anki-server-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: anki-server
    helm:
      parameters:
      - name: global.main.appSecret.autoCreate
        value: kustomize
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true