resources:
  - namespace.yml
  - application.yml
  - ingressroute.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: username1-secret
    namespace: anki-server-k8s
    envs:
      - ./.user1-secret.env
