---
apiVersion: v1
kind: Service
metadata:
  name: m1
  namespace: default
spec:
  type: ExternalName
  externalName: m1.srv.mtaha.dev
---
apiVersion: v1
kind: Service
metadata:
  name: w1
  namespace: default
spec:
  type: ExternalName
  externalName: w1.srv.mtaha.dev
---
apiVersion: v1
kind: Service
metadata:
  name: w2
  namespace: default
spec:
  type: ExternalName
  externalName: w2.srv.mtaha.dev
