---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`s3.mtaha.dev`)
    priority: 10
    services:
    - kind: Service
      name: w2
      namespace: default
      passHostHeader: true
      port: 9001
      scheme: http
  tls:
    domains:
    - main: s3.mtaha.dev
    secretName: wildcard-mtaha.dev-tls
