resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: memos-postgres
    namespace: memos-k8s
    envs:
      - ./.db-secret.env
