---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      values: |-
        configs:
          params:
            server.insecure: true
        global:
          domain: argo.mtaha.dev
        nodeSelector:
          kubernetes.io/hostname: w2.srv.mtaha.dev
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.*
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
