---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commafeed
  namespace: argocd
spec:
  destination:
    namespace: commafeed-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: commafeed
    helm:
      parameters:
      - name: global.web.options.publicUrl
        value: rss.mtaha.dev
      - name: global.postgres.secret.name
        value: commafeed-postgres
      - name: global.postgres.secret.databaseKey
        value: database
      - name: global.postgres.secret.usernameKey
        value: username
      - name: global.postgres.secret.passwordKey
        value: password
      - name: global.postgres.secret.autoCreate
        value: kustomize
      - name: global.postgres.cnpg.enabled
        value: "true"
      - name: global.postgres.cnpg.replicas
        value: "1"
      values: |-
        nodeSelector:
          kubernetes.io/hostname: m1.srv.mtaha.dev
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true