resources:
  - namespace.yml
  - ingressroute.yml
  - application.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: commafeed-postgres
    namespace: commafeed-k8s
    envs:
      - ./.db-secret.env